# Generated by Django 4.2.3 on 2024-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id主键')),
                ('nation', models.CharField(max_length=32, verbose_name='国家')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city_name', models.CharField(max_length=32, verbose_name='城市')),
                ('city_id', models.CharField(max_length=32, verbose_name='城市id')),
                ('today_dayText', models.CharField(max_length=32, verbose_name='天气状况')),
                ('today_heat', models.CharField(max_length=32, verbose_name='温度')),
                ('today_wind', models.CharField(max_length=32, verbose_name='风向风力')),
                ('weather_info', models.CharField(max_length=3000, verbose_name='7日天气')),
                ('record_date', models.CharField(max_length=32, verbose_name='记录日期')),
                ('record_time', models.CharField(max_length=32, verbose_name='记录时间')),
            ],
            options={
                'db_table': 'weatherInfo',
            },
        ),
    ]
