# Generated by Django 4.2.13 on 2024-06-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="weiboInfo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id主键"
                    ),
                ),
                (
                    "weibo_record_time",
                    models.CharField(max_length=32, verbose_name="总访问量"),
                ),
                ("weibo_rank", models.CharField(max_length=32, verbose_name="文章数")),
                ("weibo_label", models.CharField(max_length=32, verbose_name="总排名")),
                ("weibo_word", models.CharField(max_length=255, verbose_name="粉丝数")),
                ("weibo_num", models.CharField(max_length=32, verbose_name="铁粉数")),
                ("weibo_category", models.CharField(max_length=32, verbose_name="获赞数")),
            ],
            options={"db_table": "weiboInfo",},
        ),
    ]
