# Generated by Django 4.2.13 on 2024-06-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ssqInfo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id主键"
                    ),
                ),
                ("ssq_code", models.CharField(max_length=16, verbose_name="彩票期数")),
                ("ssq_date", models.CharField(max_length=32, verbose_name="出奖日期")),
                ("ssq_red", models.CharField(max_length=32, verbose_name="红球号码")),
                ("ssq_blue", models.CharField(max_length=6, verbose_name="蓝球号码")),
                ("ssq_poolmoney", models.CharField(max_length=16, verbose_name="奖池金额")),
                (
                    "ssq_content",
                    models.CharField(max_length=255, verbose_name="中奖分布信息"),
                ),
            ],
            options={
                "verbose_name": "福彩信息",
                "verbose_name_plural": "福彩信息",
                "db_table": "ssqInfo",
                "ordering": ["-ssq_code"],
            },
        ),
    ]
